### ISSUE TITLE
MinesweeperCell.isBlocked missing

### ISSUE THREAD

**Issue by nmaguirre** [nmaguirre/minesweeper#1]
Method MinesweeperCell.isBlocked is missing from class MinesweeperCell. This method should report whether the cell is blocked or not. By default, a cell is not blocked.

**Comment by gabybertorello** [comment]
MinesweeperCell.isBlocked implementada

**Comment by nricci** [comment]
Please, supply the commit hash number in order to review you modifications more easily.

**Comment by gabybertorello** [comment]
funcionalidad MinesweeperCell.isBlocked implementada (ed04daa)

**Comment by saiema** [comment]
The issue is not fixed on ed04daa but it's resolved on af5d6ae along with the implementation of class MInesweeperCell.

Please always commit the minimum code that solves a specific issue.
