### ISSUE TITLE
MinesweeperCell.isCloseTest has no tests

### ISSUE THREAD

**Issue by agustinmartinez01** [nmaguirre/minesweeper#10]

**Comment by agustinmartinez01** [comment]
Terminado  7b21175

**Comment by nricci** [comment]
Please provide a description for the issue. Also "isClosed" could be a better name for the method.

**Comment by saiema** [comment]
the existing test for `MinesweeperCell#isClose()` only tests one branch for that method.

**Comment by saiema** [comment]
Solved in #125 , please next time finish the issue.
