### ISSUE TITLE
MinesweeperCell#putMine implementation is wrong

### ISSUE THREAD

**Issue by nricci** [nmaguirre/minesweeper#101]
Please supply an implementation for putMine that is correct.

**Comment by letcharren** [comment]
related issue #14

**Comment by letcharren** [comment]
solved in commit ebff0ea

**Comment by saiema** [comment]
The `putMine()` method shouldn't be called on a blocked cell.

**Comment by saiema** [comment]
blocked status shouldn't affect the `putMine()` method.
