### ISSUE TITLE
Missing argument verification for MinesweeperBoard#numberOfMinedNeighbours(int,int)

### ISSUE THREAD

**Issue by saiema** [nmaguirre/minesweeper#103]
`MinesweeperBoard#numberOfMinedNeighbours(int,int)` must verify the coordinates passed as arguments using the method `isValidIndex(int, int)` returning an `IllegalArgumentException` if the arguments doesn't represent a valid coordinate.

Note that in issue #97 the method `isValidIndex(int,int)` must be renamed to `isValidCoordinate(int,int)`

**Comment by elisaboselli** [comment]
Resolved. Rev 72acd3f

**Comment by nricci** [comment]
Well done
