### ISSUE TITLE
Remove exception thrown from MinesweeperBoard#isValidIndex(int,int)

### ISSUE THREAD

**Issue by nricci** [nmaguirre/minesweeper#104]
MinesweeperBoard#isValidIndex(int,int) should only return a boolean value, instead this method throws an exception, fix this.

**Comment by orevitnoonairam** [comment]
Resolve in bf190d6

**Comment by nricci** [comment]
@orevitnoonairam: the commit you supplied shows changes other than the ones described by the issue

**Comment by orevitnoonairam** [comment]
@nricci I noticed that the name was changed to isValidCordenate, and changed by isValidCoordinate. Also noticed that @elnano10 was modifying the same method. Should mark this issue as duplicate?

**Comment by nricci** [comment]
Yes, you are right. I misread it and didn't notice you refactored the method name. You should if both issues are dating with the same problem. What's the issue number?

**Comment by orevitnoonairam** [comment]
@nricci #59. Supposedly this issue was responsible for correct the 59.

**Comment by nricci** [comment]
#59 is older than this issue, and also slightly different, so there is no problem.
