### ISSUE TITLE
MinesweeperBoard tests.

### ISSUE THREAD

**Issue by nricci** [nmaguirre/minesweeper#105]
Assess the quality of the test suite provided for MinesweeperBoard. The objective of this issue is to have a high quality test suite for the class. Statement coverage is the minimum. It is desirable to have plenty of negative tests.

**Comment by elisaboselli** [comment]
Solved. The missing tests belongs to others issues (#124,#114, #88). I'm not sure about how to use @Before to create a single board for all tests, specifically which constructor to use (the one that takes a number of mines or the other).
