### ISSUE TITLE
Rename rows, cols and mines number get methods in MinesweeperBoard

### ISSUE THREAD

**Issue by saiema** [nmaguirre/minesweeper#106]
Methods `getBoardRows`, `getBoardCols`, and `getBoardMines` in class `MinesweeperBoard` should have more meaningful names, since these methods return a _number of_ instead of a _collection of_

For example, `getBoardRows` can be understood as a method that return the board rows as a list. The name should indicate that the method returns how many rows the board have.

**Comment by nricci** [comment]
@saiema, @fmollea: I suggest `getMineCount`, `getRowCount`... and so on.

**Comment by fmollea** [comment]
This ready. Thanks Nico for the suggestion.
9bd0bbf

**Comment by letcharren** [comment]
after this commit, code not compile

**Comment by nricci** [comment]
Super 👍
