### ISSUE TITLE
MinesweeperGameState.numberOfRows() missing test

### ISSUE THREAD

**Issue by dmatiasr** [nmaguirre/minesweeper#109]
This test should ensure that the size of the rows is ten.

**Comment by dmatiasr** [comment]
Implementation solved 8ff8d15

**Comment by nricci** [comment]
A few things that are wrong. First, a test should end in an assertion, there is no point in testing things more things after that. If you need to test another thing, make two tests. Second, if you assert equality to 10 then asserting non equality to 11 is redundant.

**Comment by dmatiasr** [comment]
Ok, check this please : I removed test when not equals f025517
