### ISSUE TITLE
MinesweeperCell.isOpen has no Tests

### ISSUE THREAD

**Issue by elisaboselli** [nmaguirre/minesweeper#11]
MinesweeperCell.isOpen should have tests checking its expected functionality in a number of different scenarios. Statement coverage is expected from the tests of this routine.

**Comment by elisaboselli** [comment]
Ready ! :)

**Comment by saiema** [comment]
The description mentions testing under MinesweeperCell.isOpen under different scenarios but fails to mention any scenario.

In fact, the implemented test is assuming that a cell is open on creation.

**Comment by elisaboselli** [comment]
Resolved, now the cell created is open before the assert. open function is missing.
Rev. 0a747bc

**Comment by elisaboselli** [comment]
Resolved. Rev c82896b

**Comment by saiema** [comment]
Issue is resolved in rev 2cc6d69 but there's only one test. A test that evaluates the isOpen() method in the missing states.

**Comment by elisaboselli** [comment]
solved 2c0b30e (issue #57)

**Comment by saiema** [comment]
There is only one test that calls `isOpen()` (the case when it returns true) there should be at least one more test that calls `isOpen()` when it returns false.

**Comment by elisaboselli** [comment]
Resolved rev. 29d1843

**Comment by nricci** [comment]
Good job
