### ISSUE TITLE
MinesweeperGameState constructors missing.

### ISSUE THREAD

**Issue by nricci** [nmaguirre/minesweeper#110]
Provide two constructors for the class. One should create the default game (this one is already defined, the implementation is missing). An the other accept the corresponding parameters: rows, cols, mines.

**Comment by fmollea** [comment]
This ready, I'm not sure about how I done it.
92c302c

**Comment by nricci** [comment]
Very good!

**Comment by saiema** [comment]
Although this issue is closed, please note that the MinesweeperGameState(int, int, int) does not check the parameters.
