### ISSUE TITLE
MinesweeperCell.isClose has no comments

### ISSUE THREAD

**Issue by ezedepetris** [nmaguirre/minesweeper#13]
add the comment to the method is close of che clas MinesweeperCell to explain whats method do.

**Comment by saiema** [comment]
Missing description of the issue

**Comment by ezedepetris** [comment]
isse resolved in rev [bbdc73a]

**Comment by nricci** [comment]
This is a boolean query. For better javadoc documentation use the @return modifier

**Comment by ezedepetris** [comment]
resolved in rev [fc8e339]
