### ISSUE TITLE
MinesweeperCell.putMine missing

### ISSUE THREAD

**Issue by fernando13** [nmaguirre/minesweeper#14]
Method MinesweeperCell.putMine is missing from class MinesweeperCell. This method should change the state of the Cell. By default, a cell has no mine.

**Comment by saiema** [comment]
Missing description of the issue

**Comment by lbuttignol** [comment]
This method solved in this rev. 3df73ee

**Comment by nricci** [comment]
The commit number you supplied show changes that don't correspond to this issue. Please check the number and supply the correct one.

**Comment by lbuttignol** [comment]
Sorry the correct commit number is 054d85b

**Comment by saiema** [comment]
This was resolved with a bug and it's being fixed in issue #101
