### ISSUE TITLE
MinesweeperBoard.getClosedCellsCount missing

### ISSUE THREAD

**Issue by ezensich** [nmaguirre/minesweeper#148]
Method MinesweeperBoard.getClosedCellsCount is missing from the MinesweeperBoard class. This method should be return the number of cells closed from board.

**Comment by ezensich** [comment]
Resolved in https://github.com/nmaguirre/minesweeper/commit/e9f9d520738c3c2e3f919b8fe5cd4c27537da22f

**Comment by elisaboselli** [comment]
Well done ! :+1:
