### ISSUE TITLE
MinesweeperCell.putMine has no comments

### ISSUE THREAD

**Issue by lbuttignol** [nmaguirre/minesweeper#15]
MinesweeperCell.putMine has no comments describing its expected functionality. Appropriate comments should be added to this method.

**Comment by MauriDV** [comment]
solved in this rev 3e33de2

**Comment by lbuttignol** [comment]
@MauriDV Please asignate the issue before realizing it, and if the issue has assignees don't take it!

**Comment by lbuttignol** [comment]
Solved in this rev. 86dc9cd

**Comment by MauriDV** [comment]
@lbuttignol  Sorry, I didn't know it  :sweat_smile:
