### ISSUE TITLE
MinesweeperCell.open has no comments

### ISSUE THREAD

**Issue by gamassimino** [nmaguirre/minesweeper#19]

**Comment by gamassimino** [comment]
solved in this rev 2677939

**Comment by nricci** [comment]
The issue is about lacking comments in method open(). However the commit show that the change is the implementation of the method. Please respect the issue description.

**Comment by nricci** [comment]
Additionally as the method still has no comments I'm reopening the issue.

**Comment by gamassimino** [comment]
sorry, the correct commit is 1f9fb6a

**Comment by nricci** [comment]
Great! Thanks
