### ISSUE TITLE
MinesweeperCell.isBlocked has no comments

### ISSUE THREAD

**Issue by nmaguirre** [nmaguirre/minesweeper#2]
MinesweeperCell.isBlocked has no comments describing its expected functionality. Appropriate comments should be added to this method.

**Comment by nricci** [comment]
@ezensich please, provide the commit number in order to review your solution

**Comment by ezensich** [comment]
Sorry, https://github.com/nmaguirre/minesweeper/commit/920e4654c0de2051ee435b9358e2f9f6e9d92f0e

**Comment by nricci** [comment]
Well done thanks!
