### ISSUE TITLE
MinesweeperGameState.numberOfRows is missing

### ISSUE THREAD

**Issue by adriangalfioni** [nmaguirre/minesweeper#21]
Method MinesweeperGameState.numberOfRows is missing from class MinesweeperGameState. This method should return the board's rows number.

**Comment by adriangalfioni** [comment]
Resolved in commit c26a3dd5355bf8d939c630022e423e0f3a9df753

**Comment by nricci** [comment]
@adriangalfioni: you also changed the number of cols method
