### ISSUE TITLE
MinesweeperGameState.numberofColumns is missing

### ISSUE THREAD

**Issue by adriangalfioni** [nmaguirre/minesweeper#22]
Method MinesweeperGameState.numberofColumns is missing from class MinesweeperGameState. This method should return the board's columns number.

**Comment by adriangalfioni** [comment]
Resolved in commit c26a3dd5355bf8d939c630022e423e0f3a9df753

**Comment by nricci** [comment]
@adriangalfioni: same observation as in issue #21
