### ISSUE TITLE
MinesweeperBoard.MinesweeperBoard has no comments

### ISSUE THREAD

**Issue by gamassimino** [nmaguirre/minesweeper#36]

**Comment by gamassimino** [comment]
solved in this rev 541dab2

**Comment by elnano10** [comment]
not implemented matrix minesweeper examplle board[][] minesweeperCell y creation minesweeperCell

**Comment by elnano10** [comment]
board = new MinesweeperCell[rows][cols];
	  for (int r=0; r < rows;r++)
		  for (int c=0; c < cols; c++)
			  board[r][c]=new MinesweeperCell();
	}

**Comment by nricci** [comment]
The comments are ok!

@elnano10: That problem with initialization does not correspond to this issue. Also, if you committed that code (the one that initializes the matrix) check you computer for the git configuration. The commit has no associated email. Check this out --> https://help.github.com/articles/setting-your-email-in-git/
