### ISSUE TITLE
MinesweeperCell.block is missing

### ISSUE THREAD

**Issue by lbuttignol** [nmaguirre/minesweeper#41]
Method MinesweeperCell.block is missing from class MinesweeperCell.This method shuld block the cell changing the attributes

**Comment by lbuttignol** [comment]
Resolved in this rev. 627cd00

**Comment by juanpabloRV** [comment]
what happens if the block method, the cell is already blocked? double block?

**Comment by nricci** [comment]
@juanpabloRV makes a good point!

**Comment by lbuttignol** [comment]
You're right! I could ignore it but it should throw an IlegalStateException! I will work on it. Thank's

**Comment by lbuttignol** [comment]
Solved in this rev. 974728d

**Comment by lbuttignol** [comment]
I forgot to change the message of the exception. 5daf632

**Comment by nricci** [comment]
Great! Seems good for now. I'm closing it for the time being
