### ISSUE TITLE
MinesweeperCell.block has no comments

### ISSUE THREAD

**Issue by lbuttignol** [nmaguirre/minesweeper#43]
MinesweeperCell.block has no comments describing  its expected functionality. Appropriate comments should be added to this method using javadoc.

**Comment by lbuttignol** [comment]
Resolved in this rev. 56daeb7

**Comment by nricci** [comment]
@lbuttignol: the comment seems to be incomplete. Also it should read "The method blocks ...."

**Comment by lbuttignol** [comment]
Resolved in this rev. 972e603

**Comment by saiema** [comment]
The solution doesn't take into account @nricci 's comment. The javadoc should also use the `@throws` tag to document exceptions thrown by the method.

**Comment by lbuttignol** [comment]
Sorry @saiema , i thought only that tag was setting when the method expressed a " throws " in your profile. I will work on it.

**Comment by saiema** [comment]
If your method states exceptions thrown in it's profile then you must add the `@throws` tag in the javadoc. But this also applies if your method explicitly throws exceptions (like it does in this case).

**Comment by lbuttignol** [comment]
Sorry again. Solved in this rev. 90246bb
