### ISSUE TITLE
MinesweeperBoard.IsOpened missing

### ISSUE THREAD

**Issue by fernando13** [nmaguirre/minesweeper#44]
Method MinesweeperBoard.isOpened is missing from class MinesweeperBoard. This method should report whether a cell of the board is open or not.

**Comment by nricci** [comment]
Supply the commit hash

**Comment by fernando13** [comment]
issue resolved d2eb6a4af905f38250b05579e6d3fa1fd82d8e4b

**Comment by saiema** [comment]
The commit also modifies class `MinesweeperGameState`. I'll close this issue but only commit code to solve one issue at a time.
