### ISSUE TITLE
MinesweeperCell.block has no test

### ISSUE THREAD

**Issue by lbuttignol** [nmaguirre/minesweeper#46]
MinesweeperCell.block should have tests checking its expected functionality in a number of different scenarios. Statement coverage is expected from the tests of this routine.

**Comment by elisaboselli** [comment]
Resolved in two tests. One of them is for an closed cell that is being blocked and the other is for an open cell that is tried to be blocked. The second one expects an IllegalStateException.
Rev. 3a8b9d9

**Comment by nricci** [comment]
Well done.

**Comment by lbuttignol** [comment]
I made changes in the method implementation . I suggest add a test case to block a locked cell. See 974728d for more details.

**Comment by nricci** [comment]
@lbuttignol: you should put your last comment in an appropriate issue (i.e. the one that refers to the implementation of MinesweeperCell.block)

**Comment by nricci** [comment]
Fair point! Reopen the issue and make sure it's not tagged resolved.
