### ISSUE TITLE
Fix project structure

### ISSUE THREAD

**Issue by jheredia** [nmaguirre/minesweeper#47]
The structure of the project is wrong.
There is a minesweeper package inside src.main.java/minesweeper and repeated classes as well.
The MinesweeperGameState.java class should not be in the src.test.java/minesweeper directory.

**Comment by ezensich** [comment]
Please fix this.

**Comment by LuuchoRocha** [comment]
Fixed in d92528d27315305bee036ab2a5c4d5ee7b858d8f
