### ISSUE TITLE
MinesweeperCell.hasMine has no comments

### ISSUE THREAD

**Issue by jheredia** [nmaguirre/minesweeper#5]
MinesweeperCell.hasMine has no comments describing its expected functionality. Appropriate comments should be added to this method.

**Comment by dmatiasr** [comment]
Solved in this rep b7eadca

**Comment by dmatiasr** [comment]
Sorry for take this issues, and dont understood the system of assignations.

**Comment by saiema** [comment]
Issue is actually resolved in commit 75bf673

**Comment by saiema** [comment]
resolved in commit 773479c
