### ISSUE TITLE
MinesweeperCell.unblock missing

### ISSUE THREAD

**Issue by GonzalezDiana** [nmaguirre/minesweeper#50]
Method MinesweeperCell.unblock is missing from the MinesweeperCell class. This method should unblock a cell blocked.

**Comment by GonzalezDiana** [comment]
Resolved in commit ffa1953

**Comment by nricci** [comment]
@GonzalezDiana: Shouldn't the method throw an exception if the cell is not blocked?

**Comment by GonzalezDiana** [comment]
@nricci that issue is resolved in #90

**Comment by nricci** [comment]
Yes, that's correct. Well done
