### ISSUE TITLE
MinesweeperBoard.numberOfMinedNeighbours missing

### ISSUE THREAD

**Issue by GonzalezDiana** [nmaguirre/minesweeper#52]
Method MinesweeperBoard.numberOfMinedNeighbours is missing from the MinesweeperBoard class. This method should indicate the quantity of mines nearby of a cell.

**Comment by dmatiasr** [comment]
Solved in a950365

**Comment by dmatiasr** [comment]
This method was repaired re using existing methods :   1b29c5b

**Comment by nricci** [comment]
Well done
