### ISSUE TITLE
MinesweeperBoard.mark is missing

### ISSUE THREAD

**Issue by adriangalfioni** [nmaguirre/minesweeper#54]
Method MinesweeperBoard.mark is missing from the MinesweeperBoard class. This method receive the position of a cell and should block it.

**Comment by adriangalfioni** [comment]
Resolved in commit e5c18d78cd87d0e0bf66fd9bcdd04abc9b242d49

**Comment by nricci** [comment]
Very well

**Comment by jheredia** [comment]
I think that this method should throw an IllegalArgumentException if isValidCoordinate returns false.
