### ISSUE TITLE
MinesweeperGameState.mark() has no comments.

### ISSUE THREAD

**Issue by DanielSanchez94** [nmaguirre/minesweeper#55]
MinesweeperGameState.mark has no comments describing its expected functionality. Appropriate comments should be added to this method using javadoc.

**Comment by adriangalfioni** [comment]
Resolved in commit 3b6203c65078159879c3c2dae3812045cf53baa2

**Comment by juanpabloRV** [comment]
Missing comments: numberOfRows, numberofColumns, numberOfMines, gameEnded, isMarked, open.

**Comment by nricci** [comment]
@adriangalfioni: you could comment albeit briefly, what the parameters are.

@juanpabloRV: if you see something missing feel free to create issues to solve those tasks. Check that you are not duplicating an existing issue (check the closed ones as well).

**Comment by adriangalfioni** [comment]
Resolved in c292b47454110aa255d5976e97986bca30d07dff

**Comment by saiema** [comment]
There's an error in `@param row file number of the board where the cell is located.` it should say row instead of file.

**Comment by adriangalfioni** [comment]
Fixed comment in 0ab0597e52507296989297ae9a0d00de94f8adf8
