### ISSUE TITLE
MinesweeperBoard method for Neighbours 

### ISSUE THREAD

**Issue by dmatiasr** [nmaguirre/minesweeper#56]
This method should check for a mine and if the position is valid.

**Comment by dmatiasr** [comment]
Solved 219876c

**Comment by dmatiasr** [comment]
https://github.com/nmaguirre/minesweeper/issues/59
other existing method performed similar treatment. It was re using

**Comment by nricci** [comment]
This method seems redundant. From what I get from the description this is needed to compute the count of mined neighbors. I would consider deleting it. Check if that can be done. If someone else is using the method annotate it as @deprecated.

**Comment by nricci** [comment]
The method `checkValidPositionWithMine` that you wrote seems to be deleted already. I can't find the commit that did it.

**Comment by dmatiasr** [comment]
this method" checkValidPositionWithMine()" was eliminated because another partner made a similar functionality and re use( isValidIndex()), then its functionality was re named isValidCordenate().
