### ISSUE TITLE
Code format is incosistent

### ISSUE THREAD

**Issue by LuuchoRocha** [nmaguirre/minesweeper#57]
Some methods have indentation using spaces and others with spaces

**Comment by LuuchoRocha** [comment]
Fixed in 2c0b30e7949386aa01b9e4bd318f55b36cc37c00

**Comment by nricci** [comment]
@LuuchoRocha: well done. Next time try to be more specific with your issue, e.g. narrow down your class or method. Otherwise you can assign yourself the task of reviewing the whole project.
