### ISSUE TITLE
MinesweeperCell.isOpen missing

### ISSUE THREAD

**Issue by elisaboselli** [nmaguirre/minesweeper#6]
Method MinesweeperCell.isOpen is missing from class MinesweeperCell. This method should report whether the cell is open or not. By default, a cell is closed.

**Comment by saiema** [comment]
According to issue #11 isOpen() is true on cell creation. But according to this issue a cell is closed by default.

**Comment by saiema** [comment]
This issue is resolved in 75b0490 by orevitnoonairam who wasn't the person assigned to this issue.
