### ISSUE TITLE
MinesweeperBoard.putMine(row,col) implementation is missing

### ISSUE THREAD

**Issue by elnano10** [nmaguirre/minesweeper#60]
method put mine in board

**Comment by elnano10** [comment]
resolved da300f9

**Comment by nricci** [comment]
Shouldn't it check if the cell is not marked also?

**Comment by saiema** [comment]
If the arguments are not valid e.g.: `!isValidIndex(row,col)` then an exception should be thrown

**Comment by elnano10** [comment]
resolved 4bd0f1a

**Comment by elisaboselli** [comment]
well done :+1:
