### ISSUE TITLE
MinesweeperBoard.getBoardMines() has no comments.

### ISSUE THREAD

**Issue by letcharren** [nmaguirre/minesweeper#61]
MinesweeperBoard.getBoardMines() has no comments.

**Comment by letcharren** [comment]
solve in commit 3639539

**Comment by letcharren** [comment]
Missing description of the method solved in commit 3215cbd

**Comment by nricci** [comment]
@letcharren: your commit shows multiple changes, some of which don't have to do with the issue being solved.
