### ISSUE TITLE
MinesweeperBoard.open has no coments

### ISSUE THREAD

**Issue by GonzalezDiana** [nmaguirre/minesweeper#64]
MinesweeperBoard.open has no comments describing its expected functionality. Appropriate comments should be added to this method using javadoc.

**Comment by GonzalezDiana** [comment]
Resolved in commit 47579ae

**Comment by nricci** [comment]
@GonzalezDiana: your commit shows multiple changes, some of which don't have to do with the issue being solved.

In a comment, first it goes the description and then the parameters, then the return, etc. Fix this in your comment

**Comment by juanpabloRV** [comment]
It happens if you run the open procedure parameters (-10, -20)? for example.

**Comment by GonzalezDiana** [comment]
@juanpabloRV  what you are talking about, is in issue #63

**Comment by GonzalezDiana** [comment]
Comment corrections in commit acd87c6

**Comment by GonzalezDiana** [comment]
@juanpabloRV in the case of a wrong position should throw an exception. that are you referring to? in this case mark, unmarked also should do it? or you should only check that the position is valid?

**Comment by saiema** [comment]
In the last version of `MinesweeperBoard` I'm still seeing the `@param` tags before the method's description.

The comment by @juanpabloRV was for the implementation issue and not this one.

**Comment by GonzalezDiana** [comment]
Resolved in commit 9ad4902
