### ISSUE TITLE
MinesweeperBoard.mark has no test

### ISSUE THREAD

**Issue by gabybertorello** [nmaguirre/minesweeper#68]

**Comment by letcharren** [comment]
is MinesweeperBoard.Mark, MinesweeperBoard.isMark not exist

**Comment by elisaboselli** [comment]
solved bb27dd7

**Comment by nricci** [comment]
@elisaboselli: There is no point in asserting one property and then another. If you need to test both things you should make two separate tests. Tests should end with an assertion, and don't have them in the middle.

**Comment by elisaboselli** [comment]
I didn't do this test. I only looked for the commit in which it was (It's from @orevitnoonairam ) and put the label. But I will fix it later.

**Comment by nricci** [comment]
Sorry! you are right. In that case @orevitnoonairam is in charge of commenting with the issue number and tagging the issue resolved.

**Comment by elisaboselli** [comment]
Resolved. Rev 149fcbe
