### ISSUE TITLE
MinesweeperGameState.isMarked has no comments

### ISSUE THREAD

**Issue by GonzalezDiana** [nmaguirre/minesweeper#69]
MinesweeperGameState.isMarked has no comments describing its expected functionality. Appropriate comments should be added to this method using javadoc.

**Comment by GonzalezDiana** [comment]
Resolved in commit 47579ae

**Comment by nricci** [comment]
@GonzalezDiana: your commit shows multiple changes. Please only commit changes that have o do with the issue you are solving.
