### ISSUE TITLE
MinesweeperCell.isClose missing

### ISSUE THREAD

**Issue by camicalca** [nmaguirre/minesweeper#7]

**Comment by saiema** [comment]
Missing description of the issue.

**Comment by camicalca** [comment]
Method MinesweeperCell.isClose is missing from class MinesweeperCell. This method should report whether the cell is close or not. By default, a cell is closed.

**Comment by nricci** [comment]
@camicalca please provide the commit number that solved the issue

**Comment by saiema** [comment]
The issue is resolved in fa3ddf4 but with an extra an unnecessary field isClosed.
