### ISSUE TITLE
MinesweeperGameState.isMarked missing

### ISSUE THREAD

**Issue by GonzalezDiana** [nmaguirre/minesweeper#70]
Method MinesweeperGameState.isMarked is missing from the MinesweeperGameState class. This method return true if a cell is blocked.

**Comment by GonzalezDiana** [comment]
Resolved in commit 47579ae

**Comment by nricci** [comment]
@GonzalezDiana: your commit shows multiple changes. Please only commit changes that have o do with the issue you are solving.
