### ISSUE TITLE
MinesweeperBoard.putMine has no test

### ISSUE THREAD

**Issue by fernando13** [nmaguirre/minesweeper#72]
MinesweeperBoard.putMine should have test checking its expected functionality in a number of different scenarios. Statement coverage is expected from the tests of this routine

**Comment by fernando13** [comment]
Issue resolved in rev 96f7bb10d4c9f2dc95212e0c8391786018458a8f

**Comment by nricci** [comment]
Note the following: `putMineFalseTest` is a valid test, but it does not test `putMine`, remove it or see if you can make it fit into another issue. The commit shows modifications that don't have to do with the issue, this is not a good work practice.

**Comment by fernando13** [comment]
issue resolved in rev 09a9722
