### ISSUE TITLE
MinesweeperBoard.isValidIndex has no test

### ISSUE THREAD

**Issue by gamassimino** [nmaguirre/minesweeper#73]

**Comment by gamassimino** [comment]
solved in this rev 780bcbb

**Comment by nricci** [comment]
Well done

**Comment by nricci** [comment]
You have tested that the method returns true when it should. Provide more cases to test the opposite: that it will return false when given invalid indexes.

**Comment by nricci** [comment]
Also keep in mind that the method has been renamed (see issue #97). Rename your test accordingly.

**Comment by gamassimino** [comment]
fix 6719272

**Comment by elisaboselli** [comment]
well done :+1:
