### ISSUE TITLE
MinesweeperBoard.getBoardRows has no test

### ISSUE THREAD

**Issue by gamassimino** [nmaguirre/minesweeper#74]
MinesweeperBoard.getBoardRows should have tests checking its expected functionality in a number of different scenarios. Statement coverage is expected from the tests of this routine.

**Comment by lbuttignol** [comment]
Solved in this rev. e75dad6

**Comment by nricci** [comment]
A test should end with an assertion. There is no point in testing other things after the first assertion (if, for instance, it were to fail). In this case you can, and should, make two tests.

**Comment by juanpabloRV** [comment]
Missing issue description

**Comment by lbuttignol** [comment]
Solved in this rev. 87c16d7

**Comment by nricci** [comment]
Seems alright. I'm closing for the moment.
