### ISSUE TITLE
MinesweeperBoard.isOpened has no test

### ISSUE THREAD

**Issue by fernando13** [nmaguirre/minesweeper#75]
MinesweeperBoard.isOpened should have test checking its expected functionality in a number of different scenarios. Statement coverage is expected from the tests of this routine

**Comment by fernando13** [comment]
Issue resolved in rev 96f7bb10d4c9f2dc95212e0c8391786018458a8f

**Comment by nricci** [comment]
@fernando13, the changes are correct. However you added tests for put mine as well. Please work consistently with the issue tracker.
