### ISSUE TITLE
minesweeperBoard.getBoardCols has no test

### ISSUE THREAD

**Issue by gamassimino** [nmaguirre/minesweeper#76]
MinesweeperBoard.getBoardCols should have tests checking its expected functionality in a number of different scenarios. Statement coverage is expected from the tests of this routine.

**Comment by lbuttignol** [comment]
Solved in this rev a7d0a69

**Comment by nricci** [comment]
A test should end with an assertion. There is no point in testing other things after the first assertion (if, for instance, it were to fail). In this case you can, and should, make two tests.

**Comment by juanpabloRV** [comment]
Missing issue description

**Comment by lbuttignol** [comment]
Solved in this rev. 20ec21f

**Comment by nricci** [comment]
Seems alright. Closing for now.
