### ISSUE TITLE
MinesweeperBoard.mark has no comments

### ISSUE THREAD

**Issue by fernando13** [nmaguirre/minesweeper#78]
MinesweeperBoard.mark has no comments describing its expected functionality. Appropriate comments should be added to this method using javadoc.

**Comment by fernando13** [comment]
Issue resolved in rev dcf35b6cd1be874227e7ac46fe95fc767c08986a

**Comment by nricci** [comment]
Well done. @fernando13, please note that your commit shows other changes than the ones you where required to make. You should not change things you are not supposed to.
