### ISSUE TITLE
MinesweeperGameState.numberOfcolumns has no comments

### ISSUE THREAD

**Issue by camicalca** [nmaguirre/minesweeper#81]
MinesweeperGameState.numberOfcolumns has no comments describing its expected functionality. Appropriate comments should be added to this method using javadoc.

**Comment by camicalca** [comment]
ready ! ce863a0

**Comment by nricci** [comment]
The commit shows changes other than the ones you were supposed to make. Also, if you want your solution reviewed, add the resolved tag to the issue.
