### ISSUE TITLE
MinesweeperGameState.gameEnded has no comments

### ISSUE THREAD

**Issue by guttlein** [nmaguirre/minesweeper#83]
Comments of this methods are missing.

**Comment by letcharren** [comment]
solved in 8376ebd

**Comment by nricci** [comment]
@letcharren, well done. A few things to bear in mind:

- From the timeline in the issue it seems that you made the changes and then self-assigned the issue. Remember that work protocol is very important, first self-assign the issue and then do the work.

- Your commit shows changes in the method you were supposed to comment, AND CHANGES TO OTHER COMMENTS. Be very careful and limit yourself to the changes you are supposed to make. If you see something that needs to be changed USE THE ISSUE SYSTEM.

**Comment by jheredia** [comment]
I think that the javadoc for this method is not very clear. Maybe it should say:
"/**
     * Returns true if the game has ended. This method is used by other classes to see if the game has 
     * ended or not
     * @return true if this.gameEnded is true
     */
