### ISSUE TITLE
MinesweeperBoard.MinesweeperBoard() implementation constructor

### ISSUE THREAD

**Issue by elnano10** [nmaguirre/minesweeper#84]
failure to implement the creation of cells

**Comment by elnano10** [comment]
resolved 7566028

**Comment by orevitnoonairam** [comment]
I add the label resolved.

**Comment by nricci** [comment]
The changes are correct.

@elnano10 and @orevitnoonairam. Please take into consideration a couple of things:
- The person marking resolved should be the one assigned to the issue. 
- The commit number provided is the number of the merge, not the one that made the changes required by the issue
- The commit that did actually made the change has an invalid email. Please check the following link to make sure that you are committing with your proper 

https://help.github.com/articles/setting-your-email-in-git/
