### ISSUE TITLE
MinesweeperBoard.hasMine missing

### ISSUE THREAD

**Issue by fernando13** [nmaguirre/minesweeper#87]
Method MinesweeperBoard.hasMine is missing from the MinesweeperBoard class. This method return true if the cell on the position given of the board has mine, otherwise return false.

**Comment by fernando13** [comment]
Issue reolved in rev 643fb86

**Comment by nricci** [comment]
@fernando13, change only what your are supposed to. Even if you also had the comments for the method assigned you should divide the work into two different commits.
