### ISSUE TITLE
MinesweeperBoard.unMarked has no comment

### ISSUE THREAD

**Issue by gabybertorello** [nmaguirre/minesweeper#89]
MinesweeperBoard.unMarked has no comments describing its expected functionality.

**Comment by saiema** [comment]
Missing issue description

**Comment by guttlein** [comment]
Solved on https://github.com/nmaguirre/minesweeper/commit/515e3384de5a7143459f42543091034eed38179f

**Comment by elisaboselli** [comment]
well done :+1:
