### ISSUE TITLE
MinesweeperCell.hasMine has no tested

### ISSUE THREAD

**Issue by ezedepetris** [nmaguirre/minesweeper#9]
MinesweeperCell.hasMine should have test checking its expected functionality in a number of different scenarios. Statement coverage is expected from the tests of this routine

**Comment by saiema** [comment]
Missing description of the issue.

**Comment by fernando13** [comment]
Ready ed04daa

**Comment by gamassimino** [comment]
MinesweeperCellTest.hasMineTrue should not be `private`
please review this!

**Comment by adriangalfioni** [comment]
@ezedepetris still missing the description of the issue.
@fernando13 missing @Test tag in "public void hasMineFalse()"

**Comment by ezedepetris** [comment]
@adriangalfioni i create the issue when, i dont ready added to the project, then fernando take the issue before i add the description, so, i don't put the descriptions cause fernando take off me

**Comment by adriangalfioni** [comment]
Ahh okok @ezedepetris, then all the work is to @fernando13 :sweat_smile:

**Comment by fernando13** [comment]
MinesweeperCell.hasMine should have test checking its expected functionality in a number of different scenarios. Statement coverage is expected from the tests of this routine

**Comment by fernando13** [comment]
issue resolved in rev e536db7

**Comment by saiema** [comment]
The issue is resolved in commit 04e44ee
