### ISSUE TITLE
MinesweeperCellTest#isBlockedTest() testing hasMine()

### ISSUE THREAD

**Issue by saiema** [nmaguirre/minesweeper#92]
MinesweeperCellTest#isBlockedTest() is testing that after putting a mine in a cell that cell has a mine. Nothing to do with isBlocked()

Related issue : #3

**Comment by adriangalfioni** [comment]
Resolved in commit be7578ff6288703aea083fe017d945f1abe26e40 and fixed a comment in the test in 5ef162509435cc4771d286b556b7d13aaa6f715e
