### ISSUE TITLE
Rename MinesweeperBoard#isValidIndex(int, int)

### ISSUE THREAD

**Issue by saiema** [nmaguirre/minesweeper#97]
Rename method `MinesweeperBoard#isValidIndex(int, int)` to `isValidCoordenate(int,int)`

**Comment by saiema** [comment]
There is a typo in the issue's description

The new name should be `isValidCoordinate(int,int)`

**Comment by GonzalezDiana** [comment]
Resolved in commit 7bd7700

**Comment by nricci** [comment]
Well done
