### ISSUE TITLE
Fix javadoc format for MinesweeperBoard#numberOfMinedNeighbours(int,int)

### ISSUE THREAD

**Issue by saiema** [nmaguirre/minesweeper#99]
`MinesweeperBoard#numberOfMinedNeighbours(int,int)` javadoc `@return` tag should after the `@param` tags (instead of before).

**Comment by GonzalezDiana** [comment]
Resolved in commit eec3a82

**Comment by nricci** [comment]
Well done

**Comment by jheredia** [comment]
I think that the @return tag in the javadoc should not say "should indicate", this could be replaced with "indicates" so it specifies exactly what the method does.
